import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col max-h-screen'>
          <header className='shadow'>
            <Nav />
          </header>
          <main className='w-full max-h-screen overflow-y-hidden'>
            {children}
          </main>
          <footer className='mt-auto text-center'>&#169; SeSAC 2024</footer>
        </div>
      </body>
    </html>
  );
}
