@url=http://localhost:3000

### list
GET {{url}}/api/books

### search with header
GET {{url}}/api/books?q=1
Authorization: Bearer xxxsdfdasfa
user-agent: Sico

### 
POST {{url}}/api/books

{
    "title": "sample",
    "writer": "jade"
}

###
PATCH {{url}}/api/books/3

{
    "title": "new title"
}

###
DELETE {{url}}/api/books/1